services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: cool
      POSTGRES_USER: cool
      POSTGRES_PASSWORD: coolpassword
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
